# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.29
        env:
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: monitalks
          MYSQL_ROOT_PASSWORD: rpass
          MYSQL_USER: admin
          MYSQL_PASSWORD: pass
        ports:
          - "3306:3306"
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        # APPLICATION
        NODE_ENV: "test"
        PORT: 3000

        DB_HOST: "localhost"
        DB_DATABASE: "monitalks"
        DB_PORT: 3306
        DB_USER: "admin"
        DB_PASSWORD: "pass"

        APP_NAME: "MoniTalks"
        WEBHOOK_HASHER: 
        JWT_HASHER: "Yab&D4wmpPFZF$QU@C9E*YmDSZ58jnHCZSZx64z%op8oxew*R47p82h#b%obuvGW"